✨Feat: Member 피드백 반영, 폰트, 색상, 반응형, favicon
GDSC-DGU/gdsc-dgu pull request #38
Opened 2024-05-01 11:33 UTC by bunju20

## PR 타입 ( 하나 이상의 PR 타입을 선택해주세요 )

<br>

- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## 개요
<br>

### 반응형으로 수정

![CleanShot 2024-05-01 at 20 23 02@2x](https://github.com/GDSC-DGU/gdsc-dgu/assets/85238126/67b24c72-5a7c-4017-b1be-05e3eae6fbf2)

![CleanShot 2024-05-01 at 20 21 10@2x](https://github.com/GDSC-DGU/gdsc-dgu/assets/85238126/b62a910c-38c5-452c-9aa8-ef7253b6bf58)

![CleanShot 2024-05-01 at 20 21 50@2x](https://github.com/GDSC-DGU/gdsc-dgu/assets/85238126/5e4d941e-64dc-4949-86f6-4f7d6e8c2f5f)

![CleanShot 2024-05-01 at 20 22 11@2x](https://github.com/GDSC-DGU/gdsc-dgu/assets/85238126/4f2f13e0-aa81-4c99-ae70-8be41d8f2b29)

### 페비콘 추가
아래에서 검정색으로 세팅은 해놨는데, 혹시 몰라서 밝은 색도 이미지에 넣어놔서 바로 고칠수있게 만들어놨습니다.
![CleanShot 2024-05-01 at 20 26 14@2x](https://github.com/GDSC-DGU/gdsc-dgu/assets/85238126/a19c48d3-0543-4fe4-a388-c729bdc4abf2)

## 변경 사항

#29 진행했습니다. 반응형으로 변경되도록, 파비콘, 폰트 및 색상 수정하였고 자잘한 디자인 수정 완료했습니다!

## 코드 리뷰시 참고 사항

GA는 gdsc계정을 이후에 주시면 제가 달고, 메타데이터 썸네일 이슈로 서현님께서 썸네일 만드신뒤 진행하신다고 합니다!  피드백은 감사합니다!
<br>

2024-05-02 11:01 UTC, puretension approved these changes
수고많으셨습니다!!

2024-05-03 16:59 UTC, bianbbc87 approved these changes
수고하셨습니다!!

2024-05-03 17:21 UTC, seochan99 requested changes
확인했어요~ 대괄호만 바꿔주고 머지하면될듯!

2024-05-03 17:21 UTC, seochan99 commented on src/app/member/page.tsx
> +    <main className="flex flex-col items-center justify-center w-full pl-[1rem] pr-[1rem] sm:w-full md:w-100/125]lg:w-full xl:w-[75rem]">
`md:w-100/125]` 사라진 대괄호를 찾아서..

2024-05-03 17:21 UTC, seochan99 commented on src/components/member/animated/animatedBanner.tsx
> +      {children}
꿀꺽

2024-05-03 17:21 UTC, seochan99 commented on src/constants/member/devRel.ts
> +      '안녕하세요! GDSC CAU 23-24 Lead 유용민입니다. 다양한 분야에 넓게 발을 걸치고, 그중 하나에 깊게 파고드는 사람이 되고 싶습니다.',
CAU를 긁어오다니!!

2024-05-03 17:21 UTC, seochan99 commented on tailwind.config.ts
> +        sm: { max: '767px' },
체크

2024-05-04 01:24 UTC, naarang approved these changes
수고하셨습니다~!☺️

2024-05-04 02:41 UTC, seochan99 approved these changes
굿잡입니다:₩

2024-05-04 02:41 UTC, merged